# -*- coding: utf-8 -*-
"""Building Element Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzIHinP4Cbd5xzvU_TEBPgGM6PU7EXgd
"""

!pip install ultralytics

!pip show ultralytics

from google.colab import drive
drive.mount('/content/drive')

from ultralytics import YOLO
model = YOLO("yolov8x-seg.pt")

model.train(data='/content/drive/MyDrive/labelme_cl6/training_data/ARITA/YOLODataset/dataset.yaml',
            epochs=50,
            patience=0,
            imgsz=640,
            batch=8,
            workers=0,
            project='/content/drive/MyDrive/labelme_cl6/output',
            name='arita_detection_5',
            )

from ultralytics import YOLO
model = YOLO("/content/drive/MyDrive/labelme_cl6/output/arita_detection/buildv1/weights/best.pt")
results = model('/content/drive/MyDrive/labelme_cl6/4',save=True,show_boxes=False,hide_labels=True,hide_conf=True)

from google.colab import files

# ローカルからファイルをアップロード
uploaded = files.upload()

import shutil

# アップロードされたファイル名（アップロード後のファイル名を確認）
uploaded_filename = 'plotting-5.py'  # ローカルでアップロードしたファイル名

# 上書きする元のファイルパス
destination_path = '/usr/local/lib/python3.10/dist-packages/ultralytics/utils/plotting.py'

# アップロードされたファイルを元の場所に上書き
shutil.copy(uploaded_filename, destination_path)

print("ファイルが上書きされました")

!zip -r /content/semantic1.zip /content/runs/segment/predict3  #predictをファイルにする

import locale
locale.getpreferredencoding = lambda: "UTF-8"

from google.colab import files
files.download("/content/semantic.zip")