# -*- coding: utf-8 -*-
"""Environment_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n29FzADU0h3mH-pUI6xXJ5ojiGz08QFh
"""

!pip install ultralytics

from google.colab import drive
drive.mount('/content/drive')

#COCOからYOLOへ変換
from ultralytics.data.converter import convert_coco
convert_coco(
    labels_dir='/content/drive/MyDrive/datasets/coco/annotations-3',
    save_dir="/content/drive/MyDrive/coco_converted_6",
    use_segments=True,
    use_keypoints=False,
    cls91to80=True,
    lvis=False,
)

#学習フェーズ
!yolo task=segment mode=train model=yolov8x-seg.pt data=/content/drive/MyDrive/yolo/dataset.yaml epochs=150 imgsz=640 batch=-1 project=/content/drive/MyDrive/yolo/output name=detection

#test
from ultralytics import YOLO
model = YOLO("/content/drive/MyDrive/ ENVRONMENT_SEGMENTATION/yolo/output/detection16/weights/best.pt")
results = model('/content/drive/MyDrive/ ENVRONMENT_SEGMENTATION/yolo/test/Japan/ui',task='segment',save=True,show_boxes=False,hide_labels=True,hide_conf=True)

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files

# ローカルからファイルをアップロード
uploaded = files.upload()

import shutil

# アップロードされたファイル名（アップロード後のファイル名を確認）
uploaded_filename = 'plotting.py'  # ローカルでアップロードしたファイル名

# 上書きする元のファイルパス
destination_path = '/usr/local/lib/python3.11/dist-packages/ultralytics/utils/plotting.py'

# アップロードされたファイルを元の場所に上書き
shutil.copy(uploaded_filename, destination_path)

print("ファイルが上書きされました")



!zip -r /content/l.zip /content/runs/segment/predict #predictをファイルにする

import locale
locale.getpreferredencoding = lambda: "UTF-8"

from google.colab import files
files.download("/content/a.zip")